name = "command-query-user"
main = "src/index.ts"
compatibility_date = "2024-09-24"
compatibility_flags = [ "nodejs_compat" ]
[env.dev]
[env.prod]

[observability]
enabled = true

[version_metadata]
binding = "CF_VERSION_METADATA"